name: build Macos unsigned package

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v6.0.1
    - name: building package
      run: cd MacOs && sh build.sh
    - uses: actions/upload-artifact@v5.0.0
      with:
        name: server_package
        path: MacOs/NVDARemoteServer.pkg
